on:
  workflow_call:

permissions:
  contents: read
  id-token: write

env:
  GOLANG_VERSION: "1.22.3"
  GOPATH: ${{ github.workspace }}/go
  GOPRIVATE: github.com/Workiva
  REPO_ROOT: ${{ github.workspace }}/go/src/github.com/${{ github.repository }}
  DIR: ${{ github.workspace }}/go/src/github.com/${{ github.repository }}/indexers/go/semver_audit_go

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          path: ${{ env.REPO_ROOT }}
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GOLANG_VERSION }}
          cache-dependency-path: ${{ env.DIR }}/go.sum

      - name: Setup GO
        working-directory: ${{ env.DIR }}
        run: make init-dev

      - name: Build Service
        working-directory: ${{ env.DIR }}
        run: |
          make build-full
          mv semver_audit_go semver-audit-go

  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          path: ${{ env.REPO_ROOT }}

      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GOLANG_VERSION }}
          cache-dependency-path: ${{ env.DIR }}/go.sum

      - name: Setup GO
        working-directory: ${{ env.DIR }}
        run: make init-dev

      - name: Verify Formatting
        working-directory: ${{ env.DIR }}
        run: |
          go fmt ./...
          git add .
          git diff-index --stat --exit-code HEAD --

  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          path: ${{ env.REPO_ROOT }}
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GOLANG_VERSION }}
          cache-dependency-path: ${{ env.DIR }}/go.sum
      - name: Setup GO
        working-directory: ${{ env.DIR }}
        run: make init-dev

      - working-directory: ${{ env.DIR }}
        run: |
          mkdir -p test-reports
          go install github.com/tebeka/go2xunit@latest

      - name: Run Tests
        working-directory: ${{ env.DIR }}
        run: |
          go test -v -race -short -p=2 -covermode=atomic ./... 2>&1 | tee test-reports/go.log
          goTestResultCode=${PIPESTATUS[0]}
          go2xunit -input=test-reports/go.log -output=test-reports/go-xunit.xml
          go2xunitResultCode=$?
          if [ ${goTestResultCode} -ne 0 ]; then
            echo "'go test -race -short -p=2 -covermode=atomic ./...' returned non-zero exit code ${goTestResultCode}"
            exit ${goTestResultCode}
          elif [ ${go2xunitResultCode} -ne 0 ]; then
            echo "'go2xunit' returned non-zero exit code ${go2xunitResultCode}" ;
            exit ${go2xunitResultCode};
          fi

  test-functional:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GOLANG_VERSION }}
          cache-dependency-path: ${{ env.DIR }}/go.sum

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install

      - run: ./test/functional/go/run.sh
      - name: Check for gold changes
        run: |
          git diff --quiet -- ./test/functional/go || {
            echo "::error:: failed the gold file check"
            echo "::error:: Run './test/functional/go/run.sh' to regenerate these golds"
            echo ""
            git --no-pager diff \
              --src-prefix="gold/" \
              --dst-prefix="generated/" \
              -- ./test/functional/go
            exit 1
          }
